table dLojas
	lineageTag: 9838ebdd-c6f0-4112-ab80-ab39a649aa49

	column 'ID Loja'
		dataType: string
		lineageTag: 61e28981-b34e-4833-b54a-d487a73b3419
		summarizeBy: none
		sourceColumn: ID Loja

		annotation SummarizationSetBy = Automatic

	column Loja
		dataType: string
		lineageTag: 8e6b77c8-e29e-4beb-a97d-c5c041e04cd3
		summarizeBy: none
		sourceColumn: Loja

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: fae4d1d0-c6a8-4a30-9d00-c85b7fce275e
		dataCategory: Place
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	partition dLojas = m
		mode: import
		source =
				let
				    Fonte = Pdf.Tables(File.Contents("C:\Users\Funcionario\Documents\GitHub\PowerBI-Minicurso-DataDriven\Bases de Dados\Lojas.pdf"), [Implementation="1.3"]),
				    Table001 = Fonte{[Id="Table001"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Table001,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Loja", type text}, {"Loja", type text}, {"Cidade", type text}}),
				    #"Sufixo Adicionado" = Table.TransformColumns(#"Tipo Alterado1", {{"Cidade", each _ & ", Brasil", type text}})
				in
				    #"Sufixo Adicionado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

